const COMMANDS = {
  PLACE: 'PLACE',
  MOVE: 'MOVE',
  LEFT: 'LEFT',
  RIGHT: 'RIGHT',
  REPORT: 'REPORT',
  INVALID: 'INVALID'
};

const DIRECTIONS = {
  NORTH: 'NORTH',
  SOUTH: 'SOUTH',
  EAST: 'EAST',
  WEST: 'WEST'
};

const AXES = {
  X: 'x',
  Y: 'y'
};

const AXES_MAX_SIZES = {
  [AXES.X]: 4,
  [AXES.Y]: 4
};

const AXES_MIN_SIZES = {
  [AXES.X]: 0,
  [AXES.Y]: 0
};

const DIRECTIONS_TO_AXES_MAP = {
  [DIRECTIONS.NORTH]: AXES.Y,
  [DIRECTIONS.SOUTH]: AXES.Y,
  [DIRECTIONS.EAST]: AXES.X,
  [DIRECTIONS.WEST]: AXES.X,
};

const DIRECTIONS_TO_MODIFIER_MAP = {
  [DIRECTIONS.NORTH]: 1,
  [DIRECTIONS.SOUTH]: -1,
  [DIRECTIONS.EAST]: 1,
  [DIRECTIONS.WEST]: -1
};

const DIRECTIONS_SEQUENCE = [
  DIRECTIONS.NORTH,
  DIRECTIONS.EAST,
  DIRECTIONS.SOUTH,
  DIRECTIONS.WEST
];

const ROTATION_MODIFIER_MAP = {
  [COMMANDS.LEFT]: -1,
  [COMMANDS.RIGHT]: 1
};

module.exports = {
  COMMANDS,
  DIRECTIONS,
  AXES,
  AXES_MIN_SIZES,
  AXES_MAX_SIZES,
  DIRECTIONS_TO_AXES_MAP,
  DIRECTIONS_TO_MODIFIER_MAP,
  DIRECTIONS_SEQUENCE,
  ROTATION_MODIFIER_MAP
};